[package]
name = "schema-gen"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.75"
serde_json = "1.0.108"
schemars.workspace=true
oci-compat-schema.workspace=true
clap = { version = "4.4.8", features = ["derive"] }

